sudo: required
dist: trusty

language: cpp

compiler:
  - clang
  - gcc

before_install:
  - if [ "$CC" = "clang" ]; then 
      sudo apt-get update -qq
      sudo apt-get install -y libc++1 libc++-dev; 
    fi

#install:
#  - sudo apt-get update -qq
#  - sudo apt-get install -y libstdc++6
#  - sudo apt-get install -y libstdc++6-4.4-dev
      #    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
      #    - if [ "$CXX" = "clang" ]; then export CXX="clang-3.8" CC="clang-3.8"; fi

#addons:
#    apt:
#        packages:
#            - g++-5
#            - clang-3.8
#            - libc++-dev

script:
  - mkdir build
  - cd build
  - cat /home/travis/build.sh
  - cmake --version
  - cmake ..
  - make VERBOSE=1
