language: cpp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libstdc++6
  - sudo apt-get install -y libstdc++6-4.4-dev
  - (mkdir $HOME/cmake && cd $HOME/cmake && wget http://cmake.org/files/v3.4/cmake-3.4.0-rc1-Linux-x86_64.tar.gz && tar zxf cmake-*.tar.gz)

compiler:
  - clang
  - gcc

script:
  - mkdir build
  - cd build
  - $HOME/cmake/*/bin/cmake ..
  - make VERBOSE=1
