sudo: required
dist: trusty

language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
#  - sudo dpkg -l "llvm-3.7"
#  - (mkdir $HOME/cmake && cd $HOME/cmake && wget http://cmake.org/files/v3.4/cmake-3.4.0-rc1-Linux-x86_64.tar.gz && tar zxf cmake-*.tar.gz)
#  - if [ "$CXX" = "clang" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

#install:
#  - sudo apt-get update -qq
#  - sudo apt-get install -y libstdc++6
#  - sudo apt-get install -y libstdc++6-4.4-dev
      #    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
      #    - if [ "$CXX" = "clang" ]; then export CXX="clang-3.8" CC="clang-3.8"; fi

#addons:
#    apt:
#        packages:
#            - g++-5
#            - clang-3.8
#            - libc++-dev

script:
  - mkdir build
  - cd build
  - g++ --version
  - clang++ --version
  - $HOME/cmake/*/bin/cmake --version
  - $HOME/cmake/*/bin/cmake ..
  - make VERBOSE=1
