language: cpp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libstdc++6
  - sudo apt-get install -y libstdc++6-4.4-dev
  - (mkdir cmake && cd cmake && wget http://cmake.org/files/v3.4/cmake-3.4.0-rc1-Linux-x86_64.tar.gz && tar zxvf cmake-*.tar.gz)
  - export PATH="$HOME/cmake/*/bin:$PATH"
  - which cmake
  - cmake --version

compiler:
  - clang
  - gcc

script:
  - cmake --version
  - which cmake
  - mkdir build
  - cd build
  - cmake ..
  - make VERBOSE=1
